### ISSUE TITLE
'Raw resources manifest' returning returning wrong url 

### ISSUE THREAD

**Issue by PratikMahajan** [knative-scout/app-api#150]
Returning this url 
https://www.kscout.io/api.kscout.io/apps/id/serverless-example-python/deployment.json

in place of 
https://api.kscout.io/apps/id/serverless-example-python/deployment.json

**Comment by catvec** [comment]
The link is missing a URI scheme so it gets put relative to the host

https://github.com/kscout/serverless-registry-api/blob/master/handlers/deployinstructions.go#L51

**Comment by catvec** [comment]
fixed
