### ISSUE TITLE
Make natural search endpoint use fuzzy search

### ISSUE THREAD

**Issue by catvec** [knative-scout/app-api#153]
Right now it uses regexp on an "all text" index.

Make it so we use fuzzy search or something similar.

Try to use the Watson API to correct any spelling errors.

**Comment by janiejaffe** [comment]
Basic Requirements for website search:
- Endpoint searches for query within app name, tagline, description, author, tags, and categories
- Search works with incomplete word (i.e. for when user is typing out query)

**Comment by catvec** [comment]
we are doing something else now
